[package]
name = "asteroids-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30.3", features = ["bytemuck"] }
rand = "0.9.1"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = "0.30.11"
